# Generated by Django 5.2.8 on 2025-11-27 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la tarea', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la tarea', null=True, verbose_name='Descripción')),
                ('completed', models.BooleanField(default=False, help_text='Indica si la tarea está completada', verbose_name='Completada')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si la tarea fue eliminada (borrado lógico)', verbose_name='Eliminada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora de creación de la tarea', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de actualización')),
                ('user', models.ForeignKey(help_text='Usuario propietario de la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='tasks_task_user_id_bad2ed_idx'), models.Index(fields=['is_deleted', 'created_at'], name='tasks_task_is_dele_4462d3_idx')],
            },
        ),
    ]
